# -*- coding: utf-8 -*-
"""Semana01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hl9ntCi3V2wreTLf71gtWSa43vAFYkOh
"""

# Função de exibir

print('Teste')

# Variáveis

nome="Washington Fernandes de Barros"

print(nome)

ano=2026

print(ano)

# Tipo de variáves

print(type(nome))
print(type(ano))

#Estruturas condicionais

nota=5
if nota>=7:
    print("Aluno aprovado.")
else:
    print("Aluno reprovado.")

# Verificaçãp de Idade

idade=int(input("Digite sua idade: "))

if idade<18:
  print("Menor de idade.")
elif   idade==18:
  print("Você acabou de completar 18 anos")
else:
  print('Maior de idade')

#Classificação de notas Detalhadas

notaAluno=float(input("Digite a nota do aluno: "))

if notaAluno>=9.0:
  print("Resultado excelente")
elif notaAluno>=7.0:
  print("Bom desempenho")
elif notaAluno>=5.0:
  print("Passou mas foi por pouco")
else:
  print ('Reprovado')

# Estruturas de repetição

for i in range(5):
  print("Execucão Número: ",i)

# Atividade semana 1

import random

num = random.randint(0, 10)
loop=True
while loop:
  chute_usuario=int(input("Digite um chute para o número sorteado: "))
  if num>chute_usuario:
    print("O número é maior.")
  elif num<chute_usuario:
    print("O número é menor.")
  else:
    print("Parabéns, você acertou.")
    loop=False