# -*- coding: utf-8 -*-
"""Adaline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrlLuNjivFESGbMt0qAseN4Jc93fMBgK
"""

#Bibliotecas

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Função sinal

def sign(z):
  return np.where(z >= 0.5, 1.0, 0.0)

# Ativação linear

def ativacao_linear(z):
  return z

def treinar_adaline(X, d, eta=0.0005, tol=1e-6, epocas=1000):
    n_amostras, n_atributos = X.shape

    # 1. Inicialização de pesos pequenos
    w = np.random.randn(n_atributos) * 0.01
    b = 0.0  # Em Adaline, iniciar o bias em 0 é uma boa prática

    historico_custo = []

    for epoca in range(epocas):
        indices = np.random.permutation(n_amostras)

        for i in indices:
            x_i = X[i]

            # Entrada linear (Adaline não aplica degrau/sigmoide no treino)
            z = np.dot(x_i, w) + b
            y_linear = ativacao_linear(z)

            # Cálculo do erro
            erro = d[i] - y_linear

            # Regra do Delta (SGD)
            w += eta * erro * x_i
            b += eta * erro

        # 2. Custo da época calculado com os pesos atualizados (MSE)
        erros_epoca = d - (np.dot(X, w) + b)
        custo = 0.5 * np.mean(erros_epoca ** 2)
        historico_custo.append(custo)

        # 3. Critério de parada por tolerância
        if epoca > 0 and abs(historico_custo[-2] - historico_custo[-1]) < tol:
            print(f"Convergiu na época {epoca + 1}! Custo (MSE) = {custo:.6f}")
            break

    return w, b, historico_custo

from sklearn.datasets import load_iris

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

iris=load_iris()

df_iris=pd.DataFrame(data=iris.data,columns=iris.feature_names)

df_iris['target']=iris.target

X=df_iris.iloc[:,[2,3]]
y=df_iris.iloc[:,4]

setosa_versicolor = (y == 0) | (y == 1)
X = X[setosa_versicolor].values
y = y[setosa_versicolor].values

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42,stratify=y)

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

w, b, historico_custo = treinar_adaline(x_train, y_train)

print(f"Pesos finais: {w}")
print(f"Bias final: {b}")
print(f"Número de épocas até convergir: {len(historico_custo)}")
print(f"Custo final: {historico_custo[-1]:.6f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(7, 4))
plt.plot(historico_custo)
plt.xlabel("Época")
plt.ylabel("Custo (SSE)")
plt.title("Curva de Aprendizado - Adaline (Setosa vs Versicolor)")
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()

# Testando no conjunto de teste

z_teste = np.dot(x_test, w) + b
y_pred = sign(z_teste)
print(f"Acurácia no conjunto de teste: {np.mean(y_pred == y_test)}")

import numpy as np
import matplotlib.pyplot as plt

# 1. Garanta que o treinamento use x_train e y_train
w, b, historico_custo = treinar_adaline(x_train, y_train)

# 2. Defina o intervalo de x1 com base nos dados padronizados de teste (x_test)
x1_min, x1_max = x_test[:, 0].min() - 0.5, x_test[:, 0].max() + 0.5
x1_vals = np.linspace(x1_min, x1_max, 100)

# 3. Cálculo da fronteira considerando limiar = 0.5:
# w1*x1 + w2*x2 + b = 0.5  =>  x2 = (0.5 - b - w1*x1) / w2
if w[1] != 0:
    x2_vals = (0.5 - b - w[0] * x1_vals) / w[1]
else:
    x2_vals = np.zeros_like(x1_vals)

# 4. Plot dos dados de teste PADRONIZADOS
plt.figure(figsize=(8, 6))

plt.scatter(
    x_test[:, 0],
    x_test[:, 1],
    c=y_test,          # Usando y_test correto
    cmap="bwr",
    edgecolors="k",
    s=120,
    zorder=3,
    label="Amostras de Teste"
)

plt.plot(
    x1_vals,
    x2_vals,
    "g-",
    linewidth=2,
    label="Fronteira de Decisão (Limiar = 0.5)",
    zorder=2,
)

# Ajuste automático dos limites do gráfico para a escala padronizada
plt.xlim(x1_min, x1_max)
plt.ylim(x_test[:, 1].min() - 0.5, x_test[:, 1].max() + 0.5)

plt.xlabel("Comprimento da Pétala (Padronizado)")
plt.ylabel("Largura da Pétala (Padronizado)")
plt.legend(loc="upper left")
plt.title("Adaline: Fronteira de Decisão no Conjunto de Teste")
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()