# -*- coding: utf-8 -*-
"""perceptronMulticamadas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWvloYSU217sPUCIT8MuSwcV6GxPwdo6

## Redes perceptron Multicamadas
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

from tensorflow import keras

# Esse dataset já contem os dados de teste e treinamneto separados

fashion_mnist=keras.datasets.fashion_mnist


(X_train_full,y_train_full),(X_test,y_test)=fashion_mnist.load_data()

X_train_full.shape

X_test.shape

X_train_full.dtype

X_train_full[0]

# Dividindo em validação e treino, e normalizando os pixels

X_valid, X_train = X_train_full[:5000] / 255.0, X_train_full[5000:] / 255.0
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]

X_test=X_test/255.0

y_train

import matplotlib.pyplot as plt



plt.figure(figsize=(10,4))
plt.subplot(131)
plt.imshow(X_train[0],cmap='binary')
plt.title('Amostra 0')
plt.axis('off')


plt.subplot(132)
plt.imshow(X_train[1],cmap='binary')
plt.title('Amostra 1')
plt.axis('off')

plt.subplot(133)
plt.imshow(X_train[2],cmap='binary')
plt.title('Amostra 2')
plt.axis('off')

import pandas as pd

# Contagem dos objetos por classe



df_y=pd.DataFrame(y_train)
df_y.value_counts()

print(y_train)

# Criando o modelo PMC
## Declaração do modelo sequencial para o keras


model = keras.models.Sequential()

## Camada de entrada (flaten transforma a imagen 28x28 em um vetor 1d de 784 valores)

model.add(keras.layers.Flatten(input_shape=[28, 28]))

## Primeira camada escondida com 300 neuronios e funcao de ativacao ReLU
### Cada camada "Dense" gerencia seus proprios parametros, incluindo bias

model.add(keras.layers.Dense(300, activation="relu"))

## Segunda camada escondida, com 100 neuronios e relu

model.add(keras.layers.Dense(100, activation="relu"))

## Camada de saida, com 10 neuronios e funcao de ativacao softmax (multiclasse)

model.add(keras.layers.Dense(10, activation="softmax"))

model.summary()

model.layers

model.compile(loss="sparse_categorical_crossentropy",
              optimizer="sgd",
              metrics=["accuracy"])

#dados
#instanciar o modelo
# treinar
#avaliar

history=model.fit(X_train,y_train,epochs=30,
          validation_data=(X_valid,y_valid))

import pandas as pd
import matplotlib.pyplot as plt

pd.DataFrame(history.history).plot(figsize=(8, 5))
plt.grid(True)
plt.gca().set_ylim(0,1) # ajusta o eixo y para os limites de 0 a 1
plt.show()

model.evaluate(X_test,y_test)

X_new=X_test[:3]
y_proba=model.predict(X_new)
y_proba.round(2)

list(y_test[:3])

y_pred=np.argmax(y_proba,axis=1)
y_pred