# -*- coding: utf-8 -*-
"""Perceptron.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DHk8mLXunolNg_C-vAtKQYQaI1pvMIZt

## Perceptron
"""

import numpy as np

# Função Sinal

def sign(z):
    return np.where(z >0, 1, 0)

# Perceptron

def perceptron(x,w,b):
  z = np.dot(x,w)+b
  return sign(z)

# Treinamento do Perceptron (atualização exemplo por exemplo)

def treinar_perceptron(X, d, eta=0.1, epocas=1000):
    n_amostras, n_atributos = X.shape
    w = np.random.uniform(-1,1,n_atributos)
    b = np.random.uniform(-1,1)

    for epoca in range(epocas):
        erros_na_epoca = 0
        for i in range(n_amostras):
            x_i = X[i]
            y_esperado = d[i]

            z = np.dot(x_i, w) + b
            y_pred = sign(z)

            erro = y_esperado - y_pred
            if erro != 0:
                w += eta * erro * x_i
                b += eta * erro
                erros_na_epoca += 1

        # Se não houve nenhum erro nesta época, o perceptron convergiu!
        if erros_na_epoca == 0:
            print(f"Convergiu na época {epoca + 1}!")
            break

    return w, b

# Gerando os dados

n_alunos=50
mean=7
std=2

X=np.random.normal(loc=mean,scale=std,size=(n_alunos,2))
X=np.clip(X,0,10)
print(X)

# definindo os rótulos

d=(np.average(X,axis=1)>=mean)+0.0

print(d)

import matplotlib.pyplot as plt

w,b=treinar_perceptron(X,d)


# Cálculo da linha da fronteira de decisão: w1*x1 + w2*x2 + b = 0  =>  x2 = -(w1*x1 + b) / w2
x1_vals = np.linspace(-0.5, 10.0, 100)

# Evita divisão por zero caso w[1] seja 0
if w[1] != 0:
    x2_vals = -(w[0] * x1_vals + b) / w[1]
else:
    x2_vals = np.zeros_like(x1_vals)

# Plot
plt.figure(figsize=(7, 5))
plt.scatter(
    X[:, 0],
    X[:, 1],
    c=d,
    cmap="bwr",
    edgecolors="k",
    s=120,
    zorder=3,

)
plt.plot(
    x1_vals,
    x2_vals,
    "g-",
    linewidth=2,
    label="Fronteira de Decisão",
    zorder=2,
)

plt.xlim(-0.5, 12.0)
plt.ylim(-0.5, 12.0)
plt.xlabel("$x_1$")
plt.ylabel("$x_2$")
plt.legend(loc="upper right")
plt.title("Notas")
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()