# -*- coding: utf-8 -*-
"""RegressaoLogisticaNumpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJv9HF6Gp3NSYbh-eExSDKmAbY_vNpnU
"""

import numpy as np
import matplotlib.pyplot as plt

# Normalmente representamos um arranjo em python usando listas

a=[1,2,3,4,5]

for i in range (len(a)):
  a[i]=a[i]*2
print(a)

# Em numpy, as operações são vetores, portanto podem ser executadas em tempo constante

a=np.array([1,2,3,4,5])
print(a*3)

# Em arranjos bidimensionais, a vetorização é ainda mais poderosa

A=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(A)

print(np.average(A,axis=1)) #Média por linha

I=np.eye(3) #Matriz identidade
print(I)

print(np.dot(A,I)) #Multiplicação de matrizes

print(A.T) #Matriz transposta

"""## Regressão logística

$h(x)=\sigma(x \cdot w +b)$ onde:

$\sigma(z)= \frac {1}{1+e^{-z}}$
"""

def sigmoide(z):
  return 1/(1+np.exp(-z))

def logistic_regression(x,w,b):
  return sigmoide(np.dot(x,w)+b)

def gradients(X, Y, Y_hat):
    n = X.shape[0]
    dw = np.dot(X.T, (Y_hat - Y)) / n   # (2,30) x (30,1) = (2,1)
    db = np.sum(Y_hat - Y) / n          # escalar
    return dw, db

def binary_cross_entropy(Y, Y_hat, eps=1e-15):
    Y_hat = np.clip(Y_hat, eps, 1 - eps)
    n = Y.shape[0]
    loss = -np.mean(Y * np.log(Y_hat) + (1 - Y) * np.log(1 - Y_hat))
    return loss

def     gradients_decents(X,Y,epochs=10000,learning_rate=0.1):
  d=X.shape[1]

  # inicializar os pesos w e b
  w=np.random.rand(d,1)
  b=0.0

  losses=[]

  for i in range(epochs):
    # Previsão com a regressão logística

    Y_hat=logistic_regression(X,w,b)

    #Calcular os gradientes

    dw,db=gradients(X,Y,Y_hat)

    #Atualizar os pesos

    w-=learning_rate*dw
    b-=learning_rate*db

    loss=binary_cross_entropy(Y,Y_hat)
    losses.append(loss)

  plt.plot(losses)
  plt.show()

  return w,b,losses

# Gerando os dados

n_alunos=30
mean=7
std=2

X=np.random.normal(loc=mean,scale=std,size=(n_alunos,2))
X=np.clip(X,0,10)
print(X)

# definindo os rótulos

Y=(np.average(X,axis=1)>=mean)+0.0

Y = Y.reshape(-1, 1)
Y.shape

# Chamando a função do gradiente descendente

w,b,losses=gradients_decents(X,Y,epochs=10000,learning_rate=0.1)

x1_vals = np.linspace(X[:,0].min(), X[:,0].max(), 100)
x2_vals = -(w[0,0] * x1_vals + b) / w[1,0]

plt.scatter(X[:,0], X[:,1], c=Y.ravel(), cmap='bwr', edgecolors='k')
plt.plot(x1_vals, x2_vals, 'g-', linewidth=2, label='Fronteira de decisão')
plt.xlim(X[:,0].min() - 0.5, X[:,0].max() + 0.5)
plt.ylim(X[:,1].min() - 0.5, X[:,1].max() + 0.5)
plt.xlabel('x1')
plt.ylabel('x2')
plt.legend()
plt.title('Fronteira de decisão da regressão logística')
plt.show()

"""## Vetor gradiente (derivadas parciais) de função de perda entropia cruzada binária em relação aos pesos w e b para um exemplo $x_i$.

$ \frac{\partial L}{\partial w} = (\hat{y}^{(i)}-y^{(i)}).x^{(i)}$

$ \frac{\partial L}{\partial b} = (\hat{y}^{(i)}-y^{(i)})$

## Derivadas em relação ao conjunto de dados completo X, sem vetorização.

$\frac{\partial L}{\partial w}=\frac{1}{n}\displaystyle\sum_{i=1}^{n}(\hat{y}^{(i)}-y^{(i)}).x^{(i)}$

$\frac{\partial L}{\partial b}=\frac{1}{n}\displaystyle\sum_{i=1}^{n}(\hat{y}^{(i)}-y^{(i)})$

## Derivadas em relação ao conjunto de dados completo X, com vetorização.

$\frac{\partial L}{\partial w}=\frac{1}{n}X^T.(\hat{Y}-Y)$

$\frac{\partial L}{\partial b}=\frac{1}{n}\displaystyle\sum_{i=1}^{n}(\hat{y}^{(i)}-y^{(i)})$



"""