# -*- coding: utf-8 -*-
"""arvoreDeDecisao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188aXgMmYS4vOQdu2ESzFnmg2zQ9GokaE
"""

import pandas as pd
import numpy as np




import seaborn as sns
from  sklearn.ensemble import RandomForestClassifier

# Utilizando dados do scikit-learn

from sklearn.datasets  import load_iris

dados=load_iris()

X=dados.data
y=dados.target

#Dividir os dados em treinamento e teste

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.5,stratify=y,random_state=1)

# Ajuste de uma árvore de decisão

from sklearn.tree import DecisionTreeClassifier

arvore1=DecisionTreeClassifier(random_state=1)

arvore1.fit(x_train,y_train)


# Resumo (em python, podemos inspecionar os atributos da árvore)
print("\nResumo da árvore de decisão: ")
print(f'Número de nós: {arvore1.tree_.node_count}')
print(f'Profundidade da árvore: {arvore1.tree_.max_depth}')
print(f'Limiares de decisão nos nós: {arvore1.tree_.threshold}')

#Apresentação da árvore ajustada

from sklearn.tree import  plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))
plot_tree(arvore1,feature_names=dados.feature_names,class_names=dados.target_names,filled=True)
plt.show()

from sklearn.model_selection import cross_val_score

## Poda
#Poda da árvore (em python a poda é feita com ccp_alpha)
#À medida que o α aumenta, a penalidade por ter muitos nós aumenta, e a árvore fica menor.
#Árvores menores (maior alfa) são mais simples, mas geralmente têm uma impureza maior nos dados de treino.


# 1 Pegamos os candidatos a alpha

path = arvore1.cost_complexity_pruning_path(x_train, y_train)
ccp_alphas = path.ccp_alphas[:-1]



# 2. Testamos usando Validação Cruzada no x_train
cv_scores = []
for alpha in ccp_alphas:
    clf = DecisionTreeClassifier(random_state=1, ccp_alpha=alpha)
    # cv=5 divide o treino em 5 partes para testar o alpha de forma segura
    scores = cross_val_score(clf, x_train, y_train, cv=5)
    cv_scores.append(np.mean(scores))


3. # 3. Encontramos o melhor alpha baseado na validação cruzada

indice_melhor_alpha = np.argmax(cv_scores)
best_cpp_alpha = ccp_alphas[indice_melhor_alpha]

print(f'Melhor alpha encontrado (via CV): {best_cpp_alpha:.6f}')




# 4.Criamos a árvore final podada e testamos no x_test (verdadeiro teste cego)
arvore_podada = DecisionTreeClassifier(random_state=1, ccp_alpha=best_cpp_alpha)
arvore_podada.fit(x_train, y_train)

acuracia_final = arvore_podada.score(x_test, y_test)
print(f'Acurácia final da árvore podada no teste: {acuracia_final:.2%}')

# Apresentação da árvore podada

plt.figure(figsize=(20,10))
plot_tree(arvore_podada,filled=True,feature_names=dados.feature_names);
plt.show()

# Predição (considerando o modelo com "poda" )

pred_arv=arvore_podada.predict(x_test)
print('\nPrimeiras 10 preições da árvore de decisão ')
print(dados.target_names[pred_arv[:10]])

# Um bônus para ver se bateu 100% nesses primeiros 10
acertos = pred_arv[:10] == y_test[:10]
print(f'\nAcertos nos 10 primeiros: {acertos.sum()} de 10')

# Medidas de perfomance

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print('\nMatriz de confusão')
cm_arv=confusion_matrix(y_test,pred_arv)
print(cm_arv)

print("\nRelatório de classificação")
print(classification_report(y_test,pred_arv,target_names=dados.target_names))

# Acurácia=valores preditos corretamente
print(f'\nAcurácia (árvore de decisão):{accuracy_score(y_test,pred_arv):.4f}')

#Bagging

bagging=RandomForestClassifier(n_estimators=100,max_features=len(x.columns),random_state=123)
bagging.fit(x_train,y_train)
print("\nModelo bagging ajustado: ")
print(bagging)

# Avaliação do modelo (Predição bagging)

pred_bagg=bagging.predict(x_test)
print('\nMatriz de confusão (bagging): ')
cm_bagg=confusion_matrix(y_test,pred_bagg)
print(cm_bagg)

print("\nRelatório de classificação  (bagging): ")
print(classification_report(y_test,pred_bagg,target_names=labels))

print(f'\nAcurácia (bagging):{accuracy_score(y_test,pred_bagg):.4f}')

# Random forest

rf=RandomForestClassifier(n_estimators=100,max_features=2,random_state=1)
rf.fit(x_train,y_train)
print("\nModelo random forest ajustado: ")
print(rf)

# Avaliação do modelo (Predição Random Forest)
pred_rf=rf.predict(x_test)
print('\nMatriz de confusão (random forest): ')
cm_rf=confusion_matrix(y_test,pred_rf)
print(cm_rf)

print("\nRelatório de classificação  (random forest): ")
print(classification_report(y_test,pred_rf,target_names=labels))

print(f'\nAcurácia (random forest):{accuracy_score(y_test,pred_rf):.4f}')

from matplotlib.figure import figaspect
# Importância (baseado na importância das características
i_mod_rf=rf.feature_importances_
print("\nImportância das características (Random forest): ")
for feature,importance in zip(x.columns,i_mod_rf):
  print(f'{feature}:{importance:.4f}')


#varImpPlot (equivalente usando matplotlib)
importances=pd.Series(rf.feature_importances_,index=x.columns)
importances_sorted=importances.sort_values(ascending=False)

plt.figure(  figsize=(8,6))
importances_sorted.plot(kind='barh')
plt.title('Importância das variáveis (random forest)')
plt.xlabel('Importância')
plt.ylabel('Variáveis')
plt.show()

# DataFrame com os resultados

acuracia_data={'Modelo':['AD','Bagging','Random Forest'],'Holdout':[accuracy_score(y_test,pred_arv),accuracy_score(y_test,pred_bagg),accuracy_score(y_test,pred_rf)]}
acuracia_df=pd.DataFrame(acuracia_data)
acuracia_df